#!/usr/bin/env bash

export PATH="~/.bin:~/.local/bin:~/.dotfiles:$PATH"

export PROMPT_DIRTRIM=3
export HISTSIZE=
export HISTFILESIZE=
export HISTCONTROL=ignoreboth
export PROMPT_COMMAND='history -a'
export PS1='\[\e]0;\w\a\]'\
'\n\[\e[34m\]\u@\h\[\e[0m\] \[\e[36m\]\w\[\e[0m\]'\
'\n\$ '

[[ -z $(type -t __git_ps1) && -f /usr/share/git/completion/git-prompt.sh ]] && {
  \. /usr/share/git/completion/git-prompt.sh
}

[[ -n $(type -t __git_ps1) ]] && {
  export GIT_PS1_SHOWCOLORHINTS=1
  export GIT_PS1_SHOWDIRTYSTATE=1
  export GIT_PS1_SHOWSTASHSTATE=1
  export GIT_PS1_SHOWUNTRACKEDFILES=1
  export GIT_PS1_SHOWUPSTREAM=auto
  export GIT_PS1_DESCRIBE_STYLE=branch
  export PROMPT_COMMAND="$PROMPT_COMMAND;__git_ps1 '${PS1:0:-5}' '${PS1: -5}' ' %s'"
}

export BAT_THEME=Nord

eval "$(dircolors ~/.gitmodules.d/nord-dircolors/src/dir_colors)"
